# -*- coding: utf-8 -*-
"""task2_facial_rec_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-qha3RMxTMhjTluM_qOzs9ePSGD20q1r
"""

from keras.models import load_model

model = load_model('/content/drive/My Drive/facial_recog.xml')

from keras.preprocessing import image

test_image = image.load_img('/content/drive/My Drive/data/test_set/women/00000001.jpg', 
               target_size=(224,224))

type (test_image)

import numpy as np

test_image = np.expand_dims(test_image, axis=0)

test_image.shape

result = model.predict (test_image)

if result[0][0] == 1.0:
    print('men')
else:
    print('women')

